#!/bin/sh /etc/rc.common
START=99
STOP=15

install_path=/usr
bin_path=$install_path/SHS/bin

start(){          
        echo starting
	(cd $bin_path && ./daemon_SHS)
	(cd $bin_path && ./powerstart &)
	echo finished
}
restart(){
	echo stoping
	killall daemon_SHS
	killall SHS_cpp
	start
}

stop(){
	echo stoping
	killall daemon_SHS
	killall SHS_cpp
}
