#!/bin/sh
#backup some system file
if [ -f "/etc/config/system.bak" ] ; then
	rm -f /etc/config/system
else
	mv -f /etc/config/system /etc/config/system.bak
fi
if [ -f "/etc/inittab.bak" ] ; then
        rm -f /etc/config/system
else
        mv -f /etc/inittab /etc/inittab.bak
fi
